const constants = {
    POSTS_GET: 'POSTS_GET',
    POSTS_LOCAL_FILTER: 'POSTS_LOCAL_FILTER',
    POSTS_FETCHING: 'POSTS_FETCHING',
    POST_EDIT_START: 'POST_EDIT_START',
    POST_EDIT_FINISH: 'POST_EDIT_FINISH',
    POST_EDIT_CANCEL: 'POST_EDIT_CANCEL',

    OBJECTIVES_GET: 'OBJECTIVES_GET',
    OBJECTIVES_FETCHING: 'OBJECTIVES_FETCHING',

    USERS_GET: 'USERS_GET',
    USERS_FETCHING: 'USERS_FETCHING',
}

export default constants
